# Generated by Django 4.2.25 on 2025-12-01 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IGallery', '0002_album_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='IGallery.album'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photographer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='IGallery.photographer'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
