# Generated by Django 6.0 on 2025-12-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IGallery', '0004_photo_owner_photographer_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='imagen_file',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
